# Generated by Django 4.0.3 on 2022-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useritem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_username', models.CharField(max_length=200)),
                ('comment_point', models.IntegerField()),
                ('movie_genre', models.IntegerField()),
            ],
            options={
                'db_table': 'useritem',
                'managed': False,
            },
        ),
    ]
