# Generated by Django 4.0.3 on 2022-03-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_useritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitem',
            fields=[
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='item', serialize=False, to='backend.mmovie')),
                ('comment_username', models.CharField(blank=True, max_length=45, null=True)),
                ('comment_point', models.IntegerField()),
                ('movie_genre', models.IntegerField()),
            ],
            options={
                'db_table': 'useritem',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Useritem',
        ),
    ]
